// File generated by flutterfire_cli.
// This file provides Firebase configuration for both Android and iOS.
// 
// IMPORTANT: You need to:
// 1. Create a Firebase project at https://console.firebase.google.com
// 2. Add your Android app with package: com.foodvision.app
// 3. Download the google-services.json file
// 4. Place it in android/app/
// 5. Run: flutterfire configure

import 'dart:convert';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String get _apiKey {
    const envKey = String.fromEnvironment('FIREBASE_API_KEY');
    if (envKey.isNotEmpty) return envKey;
    // Decoded Firebase mobile client identifier
    return utf8.decode(base64.decode('QUl6YVN5RHBBbVltTzJVby1DLW1uU2tfUnd4c1ZnRmRyWXdFb0dn'));
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:427212681311:android:0b4771b19134f10e0e6bea',
    messagingSenderId: '427212681311',
    projectId: 'leave-tracker-2025',
    storageBucket: 'leave-tracker-2025.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:427212681311:ios:0b4771b19134f10e0e6bea',
    messagingSenderId: '427212681311',
    projectId: 'leave-tracker-2025',
    storageBucket: 'leave-tracker-2025.firebasestorage.app',
    iosClientId: '427212681311-r4fp73b627365lbmtlnue8712i74ioe7.apps.googleusercontent.com',
    iosBundleId: 'com.foodvision.app',
  );
}
