// File generated by flutterfire_cli.
// This file provides Firebase configuration for both Android and iOS.
// 
// IMPORTANT: You need to:
// 1. Create a Firebase project at https://console.firebase.google.com
// 2. Add your Android app with package: com.foodvision.app
// 3. Download the google-services.json file
// 4. Place it in android/app/
// 5. Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxxxxx', // Get from Firebase Console
    appId: '1:xxxxxxxx:android:xxxxxxxx', // Get from Firebase Console
    messagingSenderId: 'xxxxxxxx', // Get from Firebase Console
    projectId: 'your-project-id', // Get from Firebase Console
    databaseURL: 'https://your-project-id.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxxxxx', // Get from Firebase Console
    appId: '1:xxxxxxxx:ios:xxxxxxxx', // Get from Firebase Console
    messagingSenderId: 'xxxxxxxx', // Get from Firebase Console
    projectId: 'your-project-id', // Get from Firebase Console
    databaseURL: 'https://your-project-id.firebaseio.com',
    iosBundleId: 'com.foodvision.app',
  );
}
